### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-EdwinOrtiz1412#1]
[Sintesis_Edwin Ortiz Cruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-EdwinOrtiz1412/files/12704243/Sintesis_Edwin.Ortiz.Cruz.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by NoeliaGlez** [comment]
calificación: 20
